package com.toxiclens.app.pdf

data class PdfStrings(
    val reportTitle: String,
    val reportSubtitle: String,
    val reportContinued: String,
    val conversationType: String,
    val reportDate: String,
    val communicationScore: String,
    val toxicityLevel: String,
    val emotionalTone: String,
    val hiddenIntent: String,
    val greenFlags: String,
    val redFlags: String,
    val summary: String,
    val suggestedReply: String,
    val page: String,
    val generatedBy: String,
    val confidential: String,
    val warning: String
)

object PdfLanguage {

    fun get(language: String): PdfStrings {

        return if (language == "tr") {

            PdfStrings(
                reportTitle = "Konuşma Analiz Raporu",
                reportSubtitle = "Yapay Zeka Destekli İletişim Analizi",
                reportContinued = "Konuşma Analiz Raporu - Devamı",

                conversationType = "Konuşma Türü",
                reportDate = "Rapor Tarihi",

                communicationScore = "İletişim Puanı",
                toxicityLevel = "Toksisite Seviyesi",

                emotionalTone = "Duygusal Ton",
                hiddenIntent = "Gizli Niyet",
                greenFlags = "Olumlu Noktalar",
                redFlags = "Kırmızı Bayraklar",
                summary = "Genel Değerlendirme",
                suggestedReply = "Önerilen Cevap",

                page = "Sayfa",

                generatedBy = "Read Between AI tarafından oluşturuldu",

                confidential = "Gizli Rapor",

                warning =
                    "Bu analiz yapay zeka tarafından oluşturulmuştur ve yalnızca yol gösterici niteliktedir."
            )

        } else {

            PdfStrings(
                reportTitle = "Conversation Analysis Report",
                reportSubtitle = "Professional AI-Assisted Communication Report",
                reportContinued = "Conversation Analysis Report - Continued",

                conversationType = "Conversation Type",
                reportDate = "Report Date",

                communicationScore = "Communication Score",
                toxicityLevel = "Toxicity Level",

                emotionalTone = "Emotional Tone",
                hiddenIntent = "Hidden Intent",
                greenFlags = "Green Flags",
                redFlags = "Red Flags",
                summary = "Summary",
                suggestedReply = "Suggested Reply",

                page = "Page",

                generatedBy = "Generated by Read Between AI",

                confidential = "Confidential Report",

                warning =
                    "AI-generated content is supportive guidance, not definitive proof."
            )
        }
    }
}